site_name: Litmos Reporting Engine Documentation
site_url: ""
theme:
  name: material
  features: 
    - navigation.tabs
use_directory_urls: false
nav:
  - Home: index.md
  - Reports Page: reports-page.md
  - About: tech-details.md

plugins: [search, offline]